datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/java_erudio?useTimezone=true$serverTimezone=UTC
  username: root
  password:
jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: false